# Generated by Django 5.2.14 on 2026-06-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navegar_menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='contrasena',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
