# Generated by Django 5.2.14 on 2026-06-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navegar_menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='nombre_usuario_dueno',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
