# Generated by Django 5.2.15 on 2026-06-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navegar_menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='clabe',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='horario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
