# Generated by Django 5.2.13 on 2026-04-30 08:07

import django.db.models.deletion
import solicitudes_reparto.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('preparando', 'En preparación'), ('entregado_repartidor', 'Entregado a repartidor'), ('recibido', 'Recibido'), ('en_camino', 'En camino'), ('entregado_cliente', 'Entregado al cliente'), ('expirado', 'Expirado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(default=solicitudes_reparto.models.default_fecha_limite)),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitudes_reparto.repartidor')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes_reparto.restaurante')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
