# Generated by Django 5.2.14 on 2026-06-06 01:56

import django.db.models.deletion
import solicitudes_reparto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navegar_menus', '0001_initial'),
        ('registrar_cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario_repartidor', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('preparando', 'En preparación'), ('entregado_repartidor', 'Entregado a repartidor'), ('recibido', 'Recibido'), ('en_camino', 'En camino'), ('entregado_cliente', 'Entregado al cliente'), ('expirado', 'Expirado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(default=solicitudes_reparto.models.default_fecha_limite)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to='registrar_cuenta.usuario')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegar_menus.restaurante')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitudes_reparto.repartidor')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegar_menus.platillo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='solicitudes_reparto.pedido')),
            ],
        ),
    ]
