# Generated by Django 5.2.13 on 2026-05-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reparto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='contraseña',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
