# Generated by Django 5.2.14 on 2026-06-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reparto', '0002_alter_pedido_cliente_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
