# Generated by Django 5.2.13 on 2026-05-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reparto', '0002_restaurante_contraseña_restaurante_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
