# Generated by Django 5.2.14 on 2026-05-27 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navegar_menus', '0001_initial'),
        ('registrar_cuenta', '0001_initial'),
        ('solicitudes_reparto', '0003_rename_contraseña_restaurante_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to='registrar_cuenta.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='solicitudes_reparto.pedido')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegar_menus.platillo')),
            ],
        ),
    ]
