# Generated by Django 5.2.14 on 2026-06-09 07:39

import solicitudes_reparto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reparto', '0003_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, default=solicitudes_reparto.models.default_fecha_limite, null=True),
        ),
    ]
