# Generated by Django 5.2.14 on 2026-06-04 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navegar_menus', '0001_initial'),
        ('solicitudes_reparto', '0004_pedido_cliente_pedido_total_detallepedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegar_menus.restaurante'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('preparando', 'En preparación'), ('entregado_repartidor', 'Entregado a repartidor'), ('recibido', 'Recibido'), ('en_camino', 'En camino'), ('entregado_cliente', 'Entregado al cliente'), ('expirado', 'Expirado')], default='pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Restaurante',
        ),
    ]
