# Generated by Django 5.2.14 on 2026-06-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reparto', '0004_pedido_cliente_pedido_total_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
