# Generated by Django 5.2.15 on 2026-06-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reparto', '0004_alter_pedido_fecha_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='clabe',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='placas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='vehiculo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
