# Generated by Django 5.2.14 on 2026-06-03 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navegar_menus', '0001_initial'),
        ('solicitudes_reparto', '0005_pedido_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegar_menus.restaurante'),
        ),
        migrations.DeleteModel(
            name='Restaurante',
        ),
    ]
