# Generated by Django 5.2.14 on 2026-06-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reparto', '0005_alter_pedido_restaurante_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repartidor',
            name='user',
        ),
        migrations.AddField(
            model_name='repartidor',
            name='nombre_usuario_repartidor',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
