# Generated by Django 5.2.14 on 2026-06-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_reparto', '0006_alter_pedido_restaurante_delete_restaurante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repartidor',
            name='user',
        ),
        migrations.AddField(
            model_name='repartidor',
            name='nombre_usuario_repartidor',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('preparando', 'En preparación'), ('entregado_repartidor', 'Entregado a repartidor'), ('recibido', 'Recibido'), ('en_camino', 'En camino'), ('entregado_cliente', 'Entregado al cliente'), ('expirado', 'Expirado')], default='pendiente', max_length=20),
        ),
    ]
