# Generated by Django 5.2.13 on 2026-05-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(choices=[('cliente', 'Cliente'), ('repartidor', 'Repartidor'), ('restaurante', 'Restaurante')], max_length=20)),
            ],
        ),
    ]
