# Generated by Django 5.2.15 on 2026-06-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tarjeta',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
